vim.opt.breakindent = true                          -- Enable break indent
vim.opt.clipboard = 'unnamedplus'                   -- Copy/paste to system clipboard
vim.opt.cursorline = true                           -- Highlight current line
vim.opt.hlsearch = true                             -- Highlight search results
vim.opt.ignorecase = true                           -- Ignore case when searching
vim.opt.inccommand = 'split'                        -- Show live preview of substitution
vim.opt.mouse = 'a'                                 -- Enable mouse support
vim.opt.swapfile = false                            -- Don't create swap files
vim.opt.number = true                               -- Show line numbers
vim.opt.relativenumber = true                       -- Show relative line numbers
vim.opt.scrolloff = 8                               -- Keep 8 lines when scrolling
vim.opt.shell = 'bash'                              -- Use bash as the shell
vim.opt.showmode = false                            -- Don't show mode
vim.opt.signcolumn = 'yes'                          -- Always show sign column
vim.opt.smartcase = true                            -- Use case sensitive search if there is a capital letter
vim.opt.splitbelow = true                           -- Split below current window
vim.opt.splitright = true                           -- Split right of current window
vim.opt.undodir = vim.fn.stdpath('data') .. '/undo' -- Save undo history in the data directory
vim.opt.undofile = true                             -- Save undo history
vim.opt.updatetime = 250                            -- Faster completion
