vim.o.backup = false
vim.o.clipboard = vim.o.clipboard .. "unnamedplus"
vim.opt.completeopt = { "menuone", "noselect", "noinsert" }
vim.o.expandtab = true
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.lazyredraw = true
vim.o.mouse = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.shell = "bash"
vim.o.shiftwidth = 4
vim.opt.shortmess = vim.opt.shortmess + { c = true }
vim.o.showmode = false
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.softtabstop = 4
vim.o.spell = true
vim.o.spelllang = "en_gb"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = 4
vim.o.termguicolors = true
vim.o.undodir = vim.fn.stdpath "data" .. "/undo"
vim.o.undofile = true
vim.o.updatetime = 50
vim.o.wrap = false
