vim.o.clipboard = 'unnamedplus'                   -- Copy/paste to system clipboard
vim.o.ignorecase = true                           -- Ignore case when searching
vim.o.smartcase = true                            -- Use case sensitive search if there is a capital letter
vim.opt.hlsearch = true                           -- Highlight search results
vim.o.number = true                               -- Show line numbers
vim.o.relativenumber = true                       -- Show relative line numbers
vim.o.shell = 'bash'                              -- Use bash as the shell
vim.o.showmode = false                            -- Don't show mode
vim.o.splitbelow = true                           -- Split below current window
vim.o.splitright = true                           -- Split right of current window
vim.o.undodir = vim.fn.stdpath('data') .. '/undo' -- Save undo history in the data directory
vim.o.undofile = true                             -- Save undo history
vim.o.updatetime = 250
vim.opt.breakindent = true                        -- Enable break indent
vim.opt.cursorline = true                         -- Highlight current line
vim.opt.inccommand = 'split'                      -- Show live preview of substitution
vim.opt.mouse = 'a'                               -- Enable mouse support
vim.opt.scrolloff = 8                             -- Keep 8 lines when scrolling
vim.opt.signcolumn = 'yes'                        -- Always show sign column
