# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Custom config
export TERMINAL=xterm-256color
export LC_ALL=en_US.UTF-8
export EDITOR=nvim
export ZSH_TMUX_AUTOSTART=true

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="kolo"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
autojump
docker
git
git-extras
tmux
zsh-autosuggestions
zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Source all files under ~/dotfiles/source/
for FILE in $HOME/.dotfiles/source/*
do
  source $FILE
done

# Source custom files
for FILE in $HOME/.dotfiles.local/source/*
do
  test -f $FILE || continue
  source $FILE
done

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
