local icons = { 
    Array = { icon = "" },
    Boolean = { icon = "⊨" },
    Class = { icon = "ﴯ" },
    Color = { icon = "" },
    Constant = { icon = "" },
    Constructor = { icon = "" },
    Enum = { icon = "ℰ" },
    EnumMember = { icon = "" },
    Event = { icon = "🗲" },
    Field = { icon = "" },
    File = { icon = "" },
    Folder = { icon = "" },
    Function = { icon = "" },
    Interface = { icon = "" },
    Key = { icon = "" },
    Method = { icon = "ƒ" },
    Module = { icon = "" },
    Namespace = { icon = "" },
    Null = { icon = "null" },
    Number = { icon = "#" },
    Object = { icon = "⦿" },
    Operator = { icon = "" },
    Package = { icon = "" },
    Property = { icon = "" },
    Reference = { icon = "" },
    Snippet = { icon = "" },
    String = { icon = "" },
    Struct = { icon = "פּ" },
    TypeParameter = { icon = "𝙏" },
    Unit = { icon = "塞" },
    Value = { icon = "" },
    Variable = { icon = "" },
    Lsp = { icon = "" },
    Buffer = { icon = "" },
    Path = { icon = "" },
    Snippet = { icon = "" },
    Spell = { icon = "" },
    Terminal = { icon = "" },
    Tag = { icon = "炙" },
    Error = { icon = "" },
    Warn = { icon = "" },
    Hint = { icon = "" },
    Information = { icon = "" },
    Diagnostic = { icon = "" },
    CodeAction = { icon = "" },
 }

return icons
